on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Pack
        run: dotnet pack --configuration Release
      - name: Configure nuget source
        run: dotnet nuget add source --username thehexia --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/thehexia/index.json"
      - name: Deploy the package
        run: dotnet nuget push "**/bin/Release/*.nupkg" --source "github"
        